### PR TITLE
[PRO-158] Account confirmation page

### PR DESCRIPTION
**Pull request by Timmehs**
This is the landing page for account confirmation links that are emailed to the user after account creation:
confirmation email

The button/link goes to a url like:
```
https://<FRONTEND_HOST>/confirmations/:token
```

On load, the react page takes the token in the url params to try to confirm the account with the API, and then redirects to the home page with a success or failure message.

I had to put some weird useEffect logic in place to ignore the double requests that are caused by [React StrictMode](https://legacy.reactjs.org/docs/strict-mode.html) in development. Normally the double request isn't a problem, but since confirmation tokens are invalidated after use, subsequent requests fail with a 404-- so it was behaving like a failure even with valid tokens.

# Clickthrough instructions
1. Go to https://deploy-preview-29--fabulous-sprite-a61e48.netlify.app/
2. Register a new user with an email address you have access to, e.g. `mygmail+pro158@gmail.com`
3. View confirmation email and copy but DO NOT CLICK the confirmation button in the email
4. Paste the url in a text editor and copy only the `/confirmations/<some long token>` portion.
5. Go back to the preview site and paste the `/confirmations/<token from email link>`
6. You should see the confirmation loading page and get redirected with a success message.

### CODE REVIEW

**Comment by eddie-m-m** [comment]
I registered a user with my other email but haven't received a confirmation email.

**Comment by Timmehs** [comment]
Check spam/junk folders?

**Comment by eddie-m-m** [comment]
Yeah, I checked everywhere. I thought I entered the wrong address for a second but I looked at the admin dev email and it's correct.
I could always create another gmail account and try that?

**Review by eddie-m-m — APPROVED** [review]
Looks good. I was able to successfully create a new user and confirm the new account.

(Is the useEffect logic here to stay?)

**Pull request merged**
