### PR TITLE
[PRO-175] Filter by category

### PR DESCRIPTION
**Pull request by Timmehs**
Adds category filters, redesign of resource links to be more scannable.

* Filters can be shown/hidden (hidden by default)
* Image previews removed
* "Suggest a resource button" added. (TODO: Remove from contentful) (Fixes PRO-176)

image

### CODE REVIEW

**Review by eddie-m-m — COMMENTED** [review]
Everything works smoothly. It's a helpful feature which will be increasingly important as more and more resources accumulate over time.

The clickthrough revealed the difficulty of resetting the previously selected filters though. 

Can we add a small button/pill/word that enables 'clear'-ing of all currently selected filters at once? Otherwise, the user has to unclick everything they previously selected in order to e.g. select just one filter (after having selected, say, five filters).

**Comment by Timmehs** [comment]
Revisiting designs with @peiitforward, closing for now

**Review by eddie-m-m — APPROVED** [review]
Clickthrough is smooth. Features like hide filters and clear are helpful. Overall it looks great.

***Some thoughts regarding the tags:***

I'm not sure what the difference between 'Service providers' and 'Supportive services' is, especially since nothing is currently listed as a service provider when I filter for it, so I'm unsure if those need to be separated into two things (?).

Is the extra word 'services' really needed for education, mental health, housing, and legal?

Based on the people I know (but this should be considered in feedback questions with future test groups), 'Resource databases'  is not necessarily readily understood (as opposed to 'resource guides', 'resource lists', etc).  We might want to consider simplifying that language.

**Comment by Timmehs** [comment]
@eddie-m-m Gonna copy over the tags conversation into Slack for team discussion.

**Pull request merged**
