### PR TITLE
Resources loading state

### PR DESCRIPTION
**Pull request by Timmehs**
I've been wanting to leverage react-router's `deferred data` features for a while since there's a noticeable delay when navigating to pages with loaders. Reference: https://reactrouter.com/en/main/guides/deferred

Using deferred data allows the page to navigate immediately and show a "fallback" until the loader request is resolved. This PR adds a first iteration of this pattern, which can eventually be normalized and streamlined for broader use across the application (i.e. I think most of our pages with loaders should use these.

To test, try clicking between the "Search Officers" and the "Resources" pages and note the UX difference of the Search page load and the Resources page load.

image

### CODE REVIEW

**Review by eddie-m-m — APPROVED** [review]
The code looks great! 

My UX was actually _not_ good for this clickthrough. Because my internet connection at the moment is roughly 104 Mbps (per speedtest), when I click on the Resources tab I get a quick blip of the fallback before the data is almost immediately loaded. This ends up being visually disruptive (violent or jarring are the words that initially came to mind) because it occurs so quickly and the gray UI of the fallback contrasts so starkly with the colors of the loaded data. 

Overall though, I think it's safe to assume that this UX is idiosyncratic of my local system and perhaps would not be the typical UX people have.

**Comment by Timmehs** [comment]
> The code looks great!
> 
> My UX was actually _not_ good for this clickthrough. Because my internet connection at the moment is roughly 104 Mbps (per speedtest), when I click on the Resources tab I get a quick blip of the fallback before the data is almost immediately loaded. This ends up being visually disruptive (violent or jarring are the words that initially came to mind) because it occurs so quickly and the gray UI of the fallback contrasts so starkly with the colors of the loaded data.
> 
> Overall though, I think it's safe to assume that this UX is idiosyncratic of my local system and perhaps would not be the typical UX people have.

Thanks for that feedback! I don't want to ship anything thats jarring at any internet speed, so the feedback is 💯 valid and appreciated.

My primary goal is removing the time between user click and page change. Its a bad feeling to me when you click on a link and nothing happens for a few moments, hopefully you can experience that by going to the production app and clicking between resources/search https://app.projectprotocol.org/. I just expect single page apps to be snappier than that.

I lightened up the gray of the placeholders, I think the darkness of them was increasing the jarring effect, but may not totally fix what you're experiencing.

In the mobile app I had a fade-in animation for data that appeared after initial page load, but I was trying to go with the bootstrap components that were meant for this purpose 🤷 .

**Comment by Timmehs** [comment]
Note: I had to hard refresh the deploy preview to get the new placeholder colors.

**Comment by eddie-m-m** [comment]
@Timmehs The lightened gray actually does help a bit, but it is still a blip of course. I prefer the blip to a lag any day! I think it's fine for now. 
It's strange that bootstrap doesn't have something sleeker than this...

**Comment by Timmehs** [comment]
Keep an eye out for websites that have a nice async loading pattern, we can
always come back and improve it.

**Pull request merged**
