### PR TITLE
[PRO-117] Select an office modal

### PR DESCRIPTION
**Pull request by eddie-m-m**
- Create SelectOfficeModal component
- Add autofocus to searchbar on Search component
- Make search results scrollable
- Add autofocus to searchbar on SelectOfficeModal component
- Refactor Api/search bits
 
- WIP:
    - clear results after search when searchbar field is blank or modal is closed 
    - filter search results
    - add input instructions for user (?)
    - determine how results count will be displayed

### CODE REVIEW

**Comment by Timmehs** [comment]
Addressing some of the WIP things:
* Results count should be displayed as seen in the screenshot on the ticket: https://uploads.linear.app/9c3a3314-2858-46fd-a2b3-14d212b950c6/d360c6c4-1176-4a1d-a3d7-7f45bb990d93/d89b710b-2a43-4cdd-adcf-d456ce301dd6
* Re: `filter search results`, the server is filtering the search results for us using the `search` parameter, so no additional filtering is necessary.

**Comment by eddie-m-m** [comment]
- Not sure about the "No results found. Please try a different search" card. Do I need to display that on a card?
- Are we making the "Select an Office" at the top orange or black? (I don't have anything in my notes about that)

**Comment by eddie-m-m** [comment]
- Make results count grammatically correct if one result is returned (i.e. "1 Result" instead of "1 Results")

**Review by Timmehs — APPROVED** [review]
Looks good! To answer your question the modal title should be orange per the screenshot (when in doubt just match the mobile app).

**Pull request merged**
